name: Docker Image CI

on:WAWMART
  push:TESTE
    branches: [ "master" ]
  pull_request:KHI
    branches: [ "master" ]

jobs:API

  build:IOA

    runs-on: ubuntu-latest

    steps:109
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
